controller_manager:
  ros__parameters:
    update_rate: 30 #Hz
    use_sim_time: true

    ackermann_steering_controller:
      type: ackermann_steering_controller/AckermannSteeringController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # joint_state_controller:
    #   type: joint_state_controller/JointStateController

    # position_controller:
    #   type: position_controllers/JointGroupPositionController

    # velocity_controller:
    #   type: velocity_controllers/JointGroupVelocityController

    ackermann_steering_controller:
      ros__parameters:
        # publish_rate: 50
        # front_wheel_track: 1.7
        # rear_wheel_track: 1.7
        # wheelbase : 0.6
        # front_wheels_radius: 0.25
        # rear_wheels_radius: 0.4
        # use_stamped_vel: false
        # rear_wheels_names: [rear_right_wheel_joint, rear_left_wheel_joint]
        # front_wheels_names: [front_right_wheel_joint, front_right_wheel_joint]
        # base_frame_id: base_link
        # odom_frame_id: odom 
        
        
        reference_timeout: 2.0
        front_steering: true
        open_loop: false
        velocity_rolling_window_size: 10
        position_feedback: false
        use_stamped_vel: true
        rear_wheels_names: [rear_right_wheel_joint, rear_left_wheel_joint]
        front_wheels_names: [right_wheel_steer_joint, left_wheel_steer_joint]

        wheelbase: 0.6
        front_wheel_track: 1.7
        rear_wheel_track: 1.7
        front_wheels_radius: 0.25
        rear_wheels_radius: 0.4


# position_controller:
#   ros__parameters:
#     joints:
#       - front_left_servo_joint
#       - front_right_servo_joint

#     command_interfaces:
#       - position

#     state_interfaces:
#       - position

# velocity_controller:
#   ros__parameters:
#     joints:
#       - front_left_wheel_joint
#       - front_right_wheel_joint
#       - rear_left_wheel_joint
#       - rear_right_wheel_joint

#     command_interfaces:
#       - velocity 

#     state_interfaces:
#       - position
#       - velocity